import type { NameplateBlock, StaticMeasurement } from '../api/types'

export const DEFAULT_STATIC_NAMEPLATE: NameplateBlock = {
  rated_power_w: 1500.0,
  rated_voltage_v: 380.0,
  rated_current_a: 4.7,
  rated_speed_rpm: 1474.0,
  rated_torque_nm: 10.0,
  pole_pairs: 2,
  supply_freq_hz: 50.0,
  insulation_class: 'F',
  Rs: 1.405,
  Rr: 1.395,
  Ls: 0.178039,
  Lr: 0.178039,
  Lm: 0.1722,
  J: 0.0131,
}

export interface StaticFixtureCase {
  id: string
  label: string
  description: string
  expectedFault: string
  expectedZone: string
  expectedErrorCode: string
  measurement: StaticMeasurement
}

/**
 * Fixture presets extracted from steady-state runs of the Digital Twin
 * simulator (MotorPlant) at various operating points and fault states.
 * Do not invent values by hand: every number corresponds to a verified simulation point.
 */
export const STATIC_FIXTURES: StaticFixtureCase[] = [
  {
    id: 'healthy',
    label: 'Healthy Baseline (380V, 10 Nm)',
    description: 'Balanced nominal 380V supply at rated 10 Nm load, 1474 RPM steady state.',
    expectedFault: 'healthy',
    expectedZone: 'A',
    expectedErrorCode: 'SYS-OK-A',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.69,
      i_b: 4.69,
      i_c: 4.69,
      speed_rpm: 1474.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'voltage_sag',
    label: 'Voltage Sag (-12.5% balanced)',
    description: 'Symmetrical supply voltage sag to 332.5V L-L under 8 Nm load.',
    expectedFault: 'voltage_sag',
    expectedZone: 'B',
    expectedErrorCode: 'SPLY-VSAG-B',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 332.5,
      v_b: 332.5,
      v_c: 332.5,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.18,
      i_b: 4.18,
      i_c: 4.18,
      speed_rpm: 1472.6,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'supply_anomaly',
    label: 'Supply Voltage Unbalance (2.5% VUF)',
    description: 'Unbalanced grid supply voltages (Va=389.5V, Vb=Vc=375.3V) causing severe current asymmetry.',
    expectedFault: 'supply_anomaly',
    expectedZone: 'B',
    expectedErrorCode: 'SPLY-SPLY-B',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 389.5,
      v_b: 375.34,
      v_c: 375.34,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 5.79,
      i_b: 3.99,
      i_c: 3.88,
      speed_rpm: 1479.1,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'interturn_short',
    label: 'Stator Inter-Turn Short Circuit (ITSC)',
    description: 'Phase A internal turn short (eta=0.35) under balanced 380V supply, inducing negative sequence current.',
    expectedFault: 'interturn_short',
    expectedZone: 'B',
    expectedErrorCode: 'ELEC-ITS-B',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.64,
      i_b: 4.63,
      i_c: 4.32,
      speed_rpm: 1479.2,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'overload',
    label: 'Mechanical Overload (180% load)',
    description: '18 Nm shaft load (1.8x rated torque) producing 6.14A stator current and 1452.4 RPM slip.',
    expectedFault: 'overload',
    expectedZone: 'C',
    expectedErrorCode: 'PROT-OVL-C',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 6.14,
      i_b: 6.14,
      i_c: 6.14,
      speed_rpm: 1452.4,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'stall',
    label: 'Rotor Stall / Locked Rotor',
    description: 'Stalled shaft operating at 200 RPM with near locked-rotor current (14.0A).',
    expectedFault: 'stall',
    expectedZone: 'D',
    expectedErrorCode: 'PROT-STL-D',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 14.0,
      i_b: 14.0,
      i_c: 14.0,
      speed_rpm: 200.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'phase_loss',
    label: 'Single-Phasing / Phase Loss',
    description: 'Phase A disconnected (Ia=0.2A) while phases B and C carry elevated current (6.0A).',
    expectedFault: 'phase_loss',
    expectedZone: 'D',
    expectedErrorCode: 'PROT-PHL-D',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 0.2,
      i_b: 6.0,
      i_c: 6.0,
      speed_rpm: 1400.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
    },
  },
  {
    id: 'overheating',
    label: 'Thermal Overheating (Class F Exceeded)',
    description: 'Winding temperature at 145°C exceeding Class F warning threshold (140°C).',
    expectedFault: 'overheating',
    expectedZone: 'D',
    expectedErrorCode: 'THM-OVH-D',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 5.5,
      i_b: 5.5,
      i_c: 5.5,
      speed_rpm: 1465.0,
      supply_freq_hz: 50.0,
      winding_temp_c: 145.0,
      ambient_temp_c: 30.0,
    },
  },
  {
    id: 'bearing_defect',
    label: 'Bearing Outer-Race Defect (BPFO)',
    description: 'Elevated bearing envelope vibration defect peak (1.2 mm/s, overall 2.8 mm/s).',
    expectedFault: 'bearing_outer',
    expectedZone: 'C',
    expectedErrorCode: 'VIB-BRGO-C',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.69,
      i_b: 4.69,
      i_c: 4.69,
      speed_rpm: 1474.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
      vibration: {
        overall_rms_mm_s: 2.8,
        bearing_defect_mm_s: 1.2,
      },
    },
  },
  {
    id: 'misalignment',
    label: 'Shaft Angular / Parallel Misalignment',
    description: 'Pronounced 2X vibration peak (2.8 mm/s vs 1.0 mm/s 1X) indicative of coupling misalignment.',
    expectedFault: 'misalignment',
    expectedZone: 'C',
    expectedErrorCode: 'VIB-MIS-C',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.69,
      i_b: 4.69,
      i_c: 4.69,
      speed_rpm: 1474.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
      vibration: {
        overall_rms_mm_s: 3.5,
        peak_1x_mm_s: 1.0,
        peak_2x_mm_s: 2.8,
      },
    },
  },
  {
    id: 'broken_rotor_bar',
    label: 'Broken Rotor Bar (MCSA -32 dB sideband)',
    description: 'MCSA spectral sideband at fs*(1-2s) reaches -32 dB relative to 50 Hz fundamental.',
    expectedFault: 'broken_rotor_bar',
    expectedZone: 'C',
    expectedErrorCode: 'ELEC-BRB-C',
    measurement: {
      nameplate: { ...DEFAULT_STATIC_NAMEPLATE },
      v_a: 380.0,
      v_b: 380.0,
      v_c: 380.0,
      voltage_basis: 'line_line',
      value_basis: 'rms',
      i_a: 4.69,
      i_b: 4.69,
      i_c: 4.69,
      speed_rpm: 1474.0,
      supply_freq_hz: 50.0,
      ambient_temp_c: 25.0,
      spectral: {
        brb_sideband_db: -32.0,
      },
    },
  },
]
