"""initial schema

Revision ID: 6b48ca53b5bb
Revises: 
Create Date: 2026-09-25 03:30:56.654346

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '6b48ca53b5bb'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('motors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('rated_power', sa.Float(), nullable=False),
    sa.Column('rated_speed', sa.Float(), nullable=False),
    sa.Column('rated_torque', sa.Float(), nullable=False),
    sa.Column('base_load_nm', sa.Float(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=64), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('viewer', 'operator', 'admin', name='user_role'), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('username')
    )
    op.create_table('alerts',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('message', sa.String(length=255), nullable=False),
    sa.Column('acknowledged', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('alerts', schema=None) as batch_op:
        batch_op.create_index('ix_alerts_motor_ts', ['motor_id', 'ts'], unique=False)

    op.create_table('diagnoses',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('fault_type', sa.String(length=40), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('severity_score', sa.Float(), nullable=False),
    sa.Column('per_sensor_scores_json', sa.JSON(), nullable=False),
    sa.Column('source', sa.Enum('electrical_residual', 'ml_classifier', 'thermal', 'supply', 'fused', name='diag_source'), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('diagnoses', schema=None) as batch_op:
        batch_op.create_index('ix_diagnoses_motor_ts', ['motor_id', 'ts'], unique=False)

    op.create_table('faults_injected',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('fault_type', sa.String(length=40), nullable=False),
    sa.Column('severity', sa.Float(), nullable=False),
    sa.Column('params_json', sa.JSON(), nullable=False),
    sa.Column('start_ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('end_ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('created_by', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('faults_injected', schema=None) as batch_op:
        batch_op.create_index('ix_faults_motor_ts', ['motor_id', 'start_ts'], unique=False)

    op.create_table('sensors',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('type', sa.Enum('current', 'vibration', 'acoustic', 'temp', 'speed', 'voltage', name='sensor_type'), nullable=False),
    sa.Column('mode', sa.Enum('simulated', 'hardware', name='sensor_mode'), nullable=False),
    sa.Column('config_json', sa.JSON(), nullable=False),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensors', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sensors_motor_id'), ['motor_id'], unique=False)

    op.create_table('supervisory_actions',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('motor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('state', sa.String(length=16), nullable=False),
    sa.Column('load_cmd', sa.Float(), nullable=False),
    sa.Column('reason_code', sa.String(length=64), nullable=False),
    sa.Column('trip', sa.Boolean(), nullable=False),
    sa.Column('smoothed_severity', sa.Float(), nullable=True),
    sa.Column('actor', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.ForeignKeyConstraint(['motor_id'], ['motors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    with op.batch_alter_table('supervisory_actions', schema=None) as batch_op:
        batch_op.create_index('ix_supervisory_motor_ts', ['motor_id', 'ts'], unique=False)

    op.create_table('sensor_readings',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('sensor_id', sa.Integer(), nullable=False),
    sa.Column('ts', sa.DateTime().with_variant(mysql.DATETIME(fsp=6), 'mysql'), nullable=False),
    sa.Column('window_start', sa.Float(), nullable=False),
    sa.Column('window_end', sa.Float(), nullable=False),
    sa.Column('feature_vector_json', sa.JSON(), nullable=False),
    sa.Column('raw_ref', sa.LargeBinary().with_variant(mysql.MEDIUMBLOB(), 'mysql'), nullable=True),
    sa.ForeignKeyConstraint(['sensor_id'], ['sensors.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sensor_readings', schema=None) as batch_op:
        batch_op.create_index('ix_sensor_readings_sensor_ts', ['sensor_id', 'ts'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # Dropping a table drops its indexes; MySQL refuses to drop an index backing a FK first.
    for table in ("sensor_readings", "supervisory_actions", "sensors", "faults_injected", "diagnoses", "alerts",
                  "users", "motors"):
        op.drop_table(table)
